### PR TITLE
Upgrade calc module to EPICS 3.16

### PR DESCRIPTION
**Pull request by hdante**

### CODE REVIEW

**Comment by ralphlange** [comment]
Careful - Base 3.16 is not even "ready for production" yet.
Is this change compatible with 3.14 and 3.15?

**Comment by hdante** [comment]
No, this change breaks compatibility with 3.15 and is 3.16 only.

**Comment by MarkRivers** [comment]
Then we certainly don't want to merge it into the master branch.  It would need to go on a 3.16 branch in calc.

**Comment by prjemian** [comment]
I created a 3.16 branch and a 3.16 milestone in this repository.  @hdante, can you close this PR (on master) and open a new PR on the 3.16 branch?  Mark your PR with the "EPICS base 3.16" milestone.

**Comment by hdante** [comment]
Moving to another branch

**Comment by anjohnson** [comment]
Wrong solution. Instead of using a separate a branch (which would mean you have to make multiple releases, and you have to merge fixes into both branches) you should wrap the change in a conditional that tests the EPICS Base version. Here's how:
```C++
#include <epicsVersion.h>
#ifndef EPICS_VERSION_INT
#define VERSION_INT(V,R,M,P) ( ((V)<<24) | ((R)<<16) | ((M)<<8) | (P))
#define EPICS_VERSION_INT VERSION_INT(EPICS_VERSION, EPICS_REVISION, EPICS_MODIFICATION, EPICS_PATCH_LEVEL)
#endif

// ...

#if EPICS_VERSION_INT < VERSION_INT(3,16,0,1)
    pR = (sseqRecord *)(plink->value.pv_link.precord);
#else
    pR = (sseqRecord *)(plink->precord);
#endif
```

**Comment by MarkRivers** [comment]
Whoops, you're right I should not have suggested new branch.

**Comment by prjemian** [comment]
agreed

**Pull request closed without merging**
