### PR TITLE
adjust text widget box height

### LINKED ISSUE #29: userCalcs10 screen renders poorly in Phoebus
Something is wrong with the handling of the box size for the 10 widgets:
image

Not a problem for other screens, such as userArrayCalcs10:
image

### PR DESCRIPTION
**Pull request by prjemian**
- close #29

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
Looks good to me.

**Comment by MarkRivers** [comment]
Note that the failing "distutils" is because recent Python versions do not support it.  The failure can be fixed by updating the .ci submodule to the most recent release or the master branch.

**Comment by prjemian** [comment]
> Note that the failing "distutils" is because recent Python versions do not support it. The failure can be fixed by updating the .ci submodule to the most recent release or the master branch.

I don't know how to do this.  Can you suggest how?

**Comment by prjemian** [comment]
Thanks!

**Comment by MarkRivers** [comment]
I just updated .ci as follows starting at the top level of calc.
```
(base) [epics@corvette calc]$ git submodule update --init .ci
Submodule '.ci' (https://github.com/epics-base/ci-scripts) registered for path '.ci'
Cloning into '/home/epics/devel/calc-3-7-4/.ci'...
Submodule path '.ci': checked out 'e0a7c52160dd22d76ce0aa290f08a2fa200a52a1'
(base) [epics@corvette calc]$ cd .ci
(base) [epics@corvette .ci]$ git status .
HEAD detached at e0a7c52
nothing to commit, working tree clean
(base) [epics@corvette .ci]$ git tag
v1.0
v2.0.0
v2.0.1
v2.1.0
v2.2.0
v2.2.1
v2.3.0
v2.3.1
v2.3.2
v2.3.2-old
v2.3.3
v2.3.4
v2.3.5
v3.0.0
v3.0.1
v3.0.2
v3.1.0
v3.1.1
v3.2.0
v3.3.0
v3.3.0-10-g8a2666a
v3.4.0
v3.4.1
(base) [epics@corvette .ci]$ git checkout v3.4.1
Previous HEAD position was e0a7c52 Merge pull request #81 from simon-ess/update_seq_url
HEAD is now at 20f8e05 test: explicitly run tests using 'python3'
(base) [epics@corvette .ci]$ cd ..
(base) [epics@corvette calc]$ git commit -m "Update .ci to v3.4.1" .ci
[master 145393a] Update .ci to v3.4.1
 1 file changed, 1 insertion(+), 1 deletion(-)
(base) [epics@corvette calc]$ git push
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 20 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 266 bytes | 266.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:epics-modules/calc
   bd54582..145393a  master -> master
```

Now the MacOS build of calc on Github succeeds.

**Pull request merged**
