### PR TITLE
new operator INTZ(IF NEGATIVE THEN ZERO)

### PR DESCRIPTION
**Pull request by basilaljamal**
This operator put zeros where negative numbers occurs in an array, which is useful for residual gas analyzer scan waveforms.

### CODE REVIEW

**Comment by anjohnson** [comment]
Why is this new operator called `INTZ`? That word reads like a modification of `INT` to me, but it seems to have nothing to do with stripping off the fractional part. Could there be a better name that it's more obvious what operation it performs?

**Comment by basilaljamal** [comment]
INTZ became ANEG,  APOS added, ANEG and APOS test db added "aneg_apos_test.db"

Note: ANEG and APOS works on array and scalar records

**Comment by keenanlang** [comment]
From what I can see, no other operator operates on both scalar and array data. At least according to the documentation, I haven't scanned the code for undocumented capabilities. I don't necessarily have a problem with having such operators, but it would require a new category in the docs.

@anjohnson , @timmmooney , or anyone else have any view on whether to split the scalar operators out?

**Comment by basilaljamal** [comment]
ABS can operate on scalar and array records

**Comment by timmmooney** [comment]
Many operators operate on both types of data. From the docs: "Expressions supported by the array calculation record can involve scalar and/or array operands, algebraic operators and functions, trigonometric functions, relational operators, logical operators, array operators and functions, parentheses and commas, and the conditional '?:' operator. All are described in sections to follow, but first, we need to talk about how operators and functions behave when presented with scalar, array, and mixed operands."

Tim Mooney ***@***.***) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by keenanlang** [comment]
Nevermind then, I'm all good with this. Would you mind adding the commands into the documentation then?

**Pull request merged**
